dist: trusty
sudo: required
language: bash
before_install:
-curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh | bash
notifications:
  slack: devops-team-otus:9Qrn87uyDW4cYS6tJKnuF9l0
    rooms:
      secure:
bePkkfJWO1hx4KRk++V49F1F3xVOV7eWeFMdcCGHGG9bblSW9XXIW6P1C50KtzGnaBGy0oXJlch6ZDzfAerk0n4q/1RWAE3y8vl53rF3xwGWYwUSqKrw1fER4gnJLPP2+WjS6Vr0/mRHPvkMCaw4075kJIkVlTJSPZN4LMqAPhJAzoU/6FNW+0UdJpVzIugOdJ0moDR65ZCdKb2dNwE08LPhOkgwGSyRST+KORPsDMwjwdPaAa0kQ7DRhkpS1uWXdnK27fyXdgBwGsaF2yIEd3Q1F6ewKnNRvhvxoKaKqBWODpnwqYsoTNDoeOCu23ob7g7A83e/hP8M9tHYHvgethEn0HEdx3X+78mx47ep0C37//oj9kXWYmOtMOZVaWc4zSxRbRsBmyoJKOfHPop8mY01n977Zn7DflyeDq3GNw4nKrPpkYD/occ0y97m4FEJIhKR6nRYjeCLTRq5lwYJWee3oVImi055lOVYIXFTqT6MmXfEHulDz8KYum6ljQI9GStPCKwleK+d6Lz2q13NUQdJuzgf2obcx6lvJS/OkbR10cJX4kS/oMZrwnwPznGJ1B72D1FGMUUiBUwgGuvJkHad3fbXkC05lWmw41Sefk97ve+AOA2bBIaYHkOwh0PyOGwr9Lqtxw+teYfKS4iwJM2PAEvbbM9NUKcyJh0Ql44=
